#!/bin/bash
#----------------------------------------------------------------
# INSTALACION DE PERL
#----------------------------------------------------------------

#----------------------------------------------------------------
# FUNCION: imodule
# IN: Fichero tar.gz
#----------------------------------------------------------------
imodule()
{

 # tgz2src -----------------------
 if [ ! -r ./$1 ]; then echo "El fichero ./$1 NO EXISTE"; exit; fi

 cp -f ./$1 $SRCDIR
 cd $SRCDIR

 echo $1
 if [[ $1 == *.tar.gz ]]; then
   echo ">>>>> Processed as tar.gz"
   T=`echo $1 | sed s/.gz//`
   SUBDIR=`echo $1 | sed s/.tar.gz//`
   gunzip $T
   tar xvf $T
   rm -f ./$T

 elif [[ $1 == *.tgz ]]; then
   echo ">>>>> Processed as tgz"
	SUBDIR=`echo $1 | sed s/.tgz//`
   tar xzvf $1

 elif [[ $1 == *.zip ]]; then
   echo ">>>>>> Processed as zip"
   SUBDIR=`echo $1 | sed s/.zip//`
   unzip $1
 else
   exit
 fi


 # install -----------------------
 SEGUIR=1
 DIR_MODULES='/opt/cnm-extras/debian10/perl_modules'
 # Si existe /os/perl_modules/$SUBDIR.sh ejecuta ese script y termina
 if [ -f $DIR_MODULES/$SUBDIR.sh ]; then $DIR_MODULES/$SUBDIR.sh; exit; fi

 cd $SRCDIR/$SUBDIR 2>/dev/null
 if [ $? -gt 0 ];
 then
  echo INTENTANDO
  SUBDIR=`echo $SUBDIR | tr "_" "."`
  cd $SRCDIR/$SUBDIR
echo $SRCDIR/$SUBDIR
  if [ $? -gt 0 ]; then SEGUIR=0; fi
 fi


 if [ $SEGUIR -eq 1 ];
 then
  if [ -f Makefile.PL ]; then 
  	perl Makefile.PL
  	make && make install
  	cd -
  elif [ -f Build.PL ]; then
        perl Build.PL
        ./Build && ./Build install
        cd -
  else echo "*****************NO SE PUEDE INSTALAR $1"
  fi
 fi

 # Si existe /os/perl_modules/post-$SUBDIR.sh ejecuta ese script al terminar de instalar
 if [ -f $DIR_MODULES/post-$SUBDIR.sh ]; then 
   $DIR_MODULES/post-$SUBDIR.sh; 
 fi

}

#----------------------------------------------------------------
export PERL_MM_USE_DEFAULT=1
SRCDIR=/tmp/src/perl
LOGDIR=/tmp/src/perl/log
mkdir -p $SRCDIR
mkdir -p $LOGDIR
export LC_ALL=C

#----------------------------------------------------------------
# INSTALACION DE perl.5.8.5
#sh Configure -Dusethreads -d
#make
#make test
#make install
# Cambiar enlace simbolico de perl a /usr/local/bin/perl



#----------------------------------------------------------------
if [ $# -eq 1 ]; then
 if [ `echo $1 | grep -c .tar.gz` -gt 0 ]; then
  (((imodule $1) 3>&1 1>&2 2>&3|tee $LOGDIR/$1.stderr) 3>&1 1>&2 2>&3)
  if [ ! -s $LOGDIR/$1.stderr ]; then rm -f $LOGDIR/$1.stderr; fi

 elif [ `echo $1 | grep -c .tgz` -gt 0 ]; then
  (((imodule $1) 3>&1 1>&2 2>&3|tee $LOGDIR/$1.stderr) 3>&1 1>&2 2>&3)
  if [ ! -s $LOGDIR/$1.stderr ]; then rm -f $LOGDIR/$1.stderr; fi

 elif [ `echo $1 | grep -c .zip` -gt 0 ]; then
  (((imodule $1) 3>&1 1>&2 2>&3|tee $LOGDIR/$1.stderr) 3>&1 1>&2 2>&3)
  if [ ! -s $LOGDIR/$1.stderr ]; then rm -f $LOGDIR/$1.stderr; fi

 else
   for I in `cat $1`;
    do
      if [ `echo $I | grep -c tar` -gt 0 ]; then
        (((imodule $I) 3>&1 1>&2 2>&3|tee $LOGDIR/$I.stderr) 3>&1 1>&2 2>&3)
        if [ ! -s $LOGDIR/$I.stderr ]; then rm -f $LOGDIR/$I.stderr; fi
      fi
    done
 fi
else echo "USO: $0 [modulo.tar.gz|fichero]"
fi

#----------------------------------------------------------------


